# Generated by Django 3.1.7 on 2021-03-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_profile', '0002_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='email',
            field=models.EmailField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='leave',
            name='employee_id',
            field=models.CharField(default='', max_length=6),
        ),
    ]
