# Generated by Django 3.1.7 on 2021-03-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_profile', '0004_auto_20210312_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approve',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='deny',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
