# Generated by Django 3.1.7 on 2021-03-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_profile', '0007_auto_20210327_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='is_denied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
