# Generated by Django 3.1.7 on 2021-03-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_profile', '0008_auto_20210331_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='is_approved',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='is_denied',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
