# Generated by Django 3.1.7 on 2021-04-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_profile', '0013_auto_20210402_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='is_denied',
        ),
        migrations.AddField(
            model_name='leave',
            name='Approve',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
