# Generated by Django 3.1.7 on 2021-04-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_profile', '0014_auto_20210402_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='Approve',
            new_name='Approve or Deny',
        ),
    ]
