# Generated by Django 3.1.7 on 2021-04-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_profile', '0017_auto_20210402_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee_id',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
    ]
